displayName=Loadout Lab
author=AKAddons
version=0.3.2
description=Your BIS gear for any raid, boss, or mob. Simulate the best gear you have and compare vs the best in the game. Works for any combat style and reads from your bank, inventory, equipment, STASH storage and more.
tags=gear,bis,best,slot,dps,loadout,equipment,bossing
plugins=com.loadoutlab.LoadoutLabPlugin
build=standard
