package com.loadoutlab.ui;

import com.google.gson.JsonObject;
import com.loadoutlab.data.JsonResources;
import java.util.HashMap;
import java.util.Map;
import net.runelite.api.gameval.SpriteID;

/**
 * Icon lookups for the compact "assumes" rows: prayer names to prayer-book
 * sprites, boost labels to potion/heart item ids, and spell names to
 * spellbook sprites - so the panel can show a small icon instead of a
 * sentence. Names must match PrayerBonuses / BoostProfile / SpellStats
 * exactly; unmapped names fall back to plain text.
 */
final class AssumeIcons
{
	/** Generated by scripts/gen_assume_icons.py; drift-guarded by
	 * AssumeIconsDriftTest, which re-reflects the SpriteID constants at
	 * build time so an upstream renumbering goes red instead of quietly
	 * painting the wrong icon. */
	private static final String RESOURCE = "/com/loadoutlab/data/assume_icons.json";

	private static final Map<String, Integer> PRAYERS = new HashMap<>();
	private static final Map<String, Integer> BOOST_ITEMS = new HashMap<>();
	private static final Map<String, Integer> SPELLS = new HashMap<>();

	static
	{
		// Fail-soft on purpose: these are decoration, and an unmapped name
		// already has a plain-text fallback below.
		JsonObject root = JsonResources.object(RESOURCE);
		JsonResources.stringIntMap(root, "prayers", PRAYERS);
		JsonResources.stringIntMap(root, "boostItems", BOOST_ITEMS);
		JsonResources.stringIntMap(root, "spells", SPELLS);
	}

	private AssumeIcons()
	{
	}

	/** Prayer-book sprite id for this prayer name, or -1. */
	static int prayerSprite(String name)
	{
		return PRAYERS.getOrDefault(name, -1);
	}

	/** Skill icon for a combat style - melee wears the Attack icon. Sprites,
	 * never font glyphs (Tahoe tofu rule); tooltips carry the words. */
	static int styleSprite(com.loadoutlab.engine.CombatStyle style)
	{
		switch (style)
		{
			case RANGED:
				return SpriteID.Staticons.RANGED;
			case MAGIC:
				return SpriteID.Staticons.MAGIC;
			default:
				return SpriteID.Staticons.ATTACK;
		}
	}

	/** Item id whose icon represents this boost label, or -1. */
	static int boostItem(String label)
	{
		return BOOST_ITEMS.getOrDefault(label, -1);
	}

	/** Spellbook sprite id for this spell name, or -1. */
	static int spellSprite(String name)
	{
		return SPELLS.getOrDefault(name, -1);
	}
}
