#!/usr/bin/env python3
"""Regenerate src/main/resources/com/loadoutlab/data/stash-units.tsv.

Source of truth: the StashUnit enum in Dude, Where's My Stuff
(github.com/Thource/dude-wheres-my-stuff, BSD-2 - see
licenses/dude-wheres-my-stuff-LICENSE), itself derived from RuneLite
core's clue-scroll data. Each STASH unit row carries the text shown on
the in-game STASH chart (widget 493) and the unit's default item ids -
what a FILLED unit is assumed to hold.

Usage:
  javap -p -constants -classpath <runelite-api.jar> \
      net.runelite.api.gameval.ItemID > /tmp/itemid.txt
  python3 scripts/gen_stash_units.py <path/to/StashUnit.java> /tmp/itemid.txt

Exit code is the gate: non-zero on any unresolved ItemID constant or a
suspicious unit count.
"""
import re
import sys
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / \
    "src/main/resources/com/loadoutlab/data/stash-units.tsv"
EXPECTED_MIN_UNITS = 100  # 118 at generation time; more may be added


def main() -> int:
    if len(sys.argv) != 3:
        print(__doc__)
        return 2
    src = Path(sys.argv[1]).read_text()
    ids = {
        m.group(1): int(m.group(2))
        for m in re.finditer(
            r"public static final int (\w+) = (\d+);",
            Path(sys.argv[2]).read_text())
    }

    body = src[src.index("public enum StashUnit {"):]
    rows = []
    pattern = re.compile(
        r"\n  ([A-Z0-9_]+)\(\s*\n\s*\"((?:[^\"\\]|\\.)*)\",\s*\n\s*"
        r"\"((?:[^\"\\]|\\.)*)\",.*?new int\[\]\{([^}]*)\}",
        re.S)
    for m in pattern.finditer(body):
        chart_text = m.group(3).replace('\\"', '"').replace("\\\\", "\\")
        item_ids = []
        for token in m.group(4).split(","):
            token = token.strip()
            if not token:
                continue
            name = token.split(".")[-1]
            if name not in ids:
                print(f"UNRESOLVED ItemID constant: {token} ({m.group(1)})")
                return 1
            item_ids.append(ids[name])
        if not item_ids:
            print(f"STASH unit with no default items: {m.group(1)}")
            return 1
        rows.append((chart_text, item_ids))

    if len(rows) < EXPECTED_MIN_UNITS:
        print(f"Only {len(rows)} units parsed - source format changed?")
        return 1

    lines = [
        "# Generated by scripts/gen_stash_units.py - do not edit by hand.",
        "# Data: Dude, Where's My Stuff StashUnit enum (BSD-2, see",
        "# licenses/dude-wheres-my-stuff-LICENSE), derived from RuneLite core",
        "# clue data. Columns: <chart text>\\t<default item ids, comma-joined>.",
    ]
    for chart_text, item_ids in sorted(rows):
        lines.append(chart_text + "\t" + ",".join(str(i) for i in item_ids))
    OUT.write_text("\n".join(lines) + "\n")
    print(f"Wrote {len(rows)} STASH units to {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
